version: 2.1

orbs:
  ci: bigcommerce/internal@volatile
  php: bigcommerce/internal-php@volatile

jobs_default: &jobs_default
  e:
    name: php/php
    php-version: << matrix.php-version >>
  matrix:
    parameters:
      php-version: [ "8.1", "8.2" ]


workflows:
  version: 2
  all-tests:
    jobs:
      - php/phpunit-tests:
          <<: *jobs_default
          minimum_coverage: 40
      - php/static-analysis:
          <<: *jobs_default
          generate_ide_helper: false
