version: 2.1

orbs:
  ci: bigcommerce/internal@volatile
  php: bigcommerce/internal-php@volatile

jobs:
  tests:
    parameters:
      php-version:
        type: string
    executor:
      name: php/php
      php-version: << parameters.php-version >>
    steps:
      - ci/pre-setup
      - php/composer-install
      - php/unit-phpunit
      - run: ./script/phpstan

workflows:
  version: 2
  all-tests:
    jobs:
      - tests:
          matrix:
            parameters:
              php-version: ["8.0"]
